name: Feature

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: go build -v ./...
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        run: go vet -v ./...
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: go test -v ./...
  test-race:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: go test -race -v ./...
