name: Feature

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Установка Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3
      - name: Выгрузка кода
        uses: actions/checkout@v4
      - name: Сборка
        run: go build -v ./...
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
      - uses: actions/checkout@v4
      - name: Запуск unit-тестов
        run: go test -v -count=1 ./...
  test-race:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
      - uses: actions/checkout@v4
      - name: Проверка гонок
        run: go test -v -race ./...
  lint:
    needs:
      - test
      - test-race
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
      - uses: actions/checkout@v4
      - name: Проверка код-стайла
        run: go vet -v ./...

