name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: go build -v ./...
