name: Feature

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Установка Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3
      - name: Выгрузка кода
        uses: actions/checkout@v4
      - name: Сборка
        run: go build -v ./...
